[workspace]
resolver = "2"
members = [
  "crates/tuir-core",
  "crates/tuir-tui",
  "crates/tuir-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["proycon"]
repository = "https://github.com/proycon/tuir-rust"
rust-version = "1.85.0"

[profile.dev]
opt-level = 0

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
