[package]
name = "tuir-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "tuir"
path = "src/main.rs"

[dependencies]
tuir-core = { path = "../tuir-core" }
tuir-tui = { path = "../tuir-tui" }

# CLI
clap = { version = "4", features = ["derive"] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"

# Error handling
anyhow = "1"
color-eyre = "0.6"

# Term
dirs = "5"
